<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Events_searchInputEvent</name>
   <tag></tag>
   <elementGuidId>eb15697d-f056-451c-b812-0e2cb15cfe7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchInputEvent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchInputEvent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc960269-88d7-4f0f-8501-6a51a2733de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchInputEvent</value>
      <webElementGuid>4ab358f6-f701-4ed3-913e-877aa62a2075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>05ce309a-194e-4b26-a9e5-10a8380ecae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87e8a328-b749-406c-aeea-8449f50c04b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control searchinput</value>
      <webElementGuid>5295edda-51d6-48d5-a7b4-a9b99d8db3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>367f11bd-3d5b-424f-b9bb-b4cecec18759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchInputEvent&quot;)</value>
      <webElementGuid>2afb40d7-272e-404e-8657-f9883bc0eb74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchInputEvent']</value>
      <webElementGuid>f6171386-319e-4e8d-9485-7833c8e844e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='containerEvent']/div/div/div[2]/input</value>
      <webElementGuid>cadee15a-706d-4a85-b697-c597293e7946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c392b0a6-9f8f-482c-9fba-79e2cbfc5c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchInputEvent' and @type = 'text' and @placeholder = '']</value>
      <webElementGuid>934e1b12-0218-49f1-b543-18ac827f93d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
